source 'https://supermarket.chef.io'

cookbook 'mycookbook', path: './chef/cookbooks/mycookbook'
cookbook 'selinux'
cookbook 'sudo'
cookbook 'users'
cookbook 'tomcat'
cookbook 'java'
cookbook 'haproxy', git: 'https://github.com/sous-chefs/haproxy.git', tag: 'v5.0.2'
cookbook 'nrpe'
